.Dd August 12, 2013
.Dt CHRC 1
.Os
.Sh NAME
.Nm chrc
.Nd modify tags for existing dotfiles
.Sh SYNOPSIS
.Nm chrc
.Op Fl qvOU
.Op Fl D Ar NEW-DIR
.Op Fl T Ar NEW-TAG
.Ar FILES ...
.Sh DESCRIPTION
Change the tag, host-specificity, or dotfiles directory for an existing
list of
.Va FILES
already in a dotfiles directory.
.
.Bl -tag
.It Fl D Ar NEW-DIR
move
.Va FILES
into
.Va NEW-DIR
.
.It Fl O
move
.Va FILES
into the host-specific directory
.It Fl q
decrease verbosity
.
.It Fl T Ar NEW-TAG
assign a new tag to
.Va FILES
.
.It Fl U
strip
.Va FILES
of all tags
.
.It Fl v
increase verbosity. This can be repeated for extra verbosity.
.El
.Sh FILES
.Pa ~/.dotfiles
.Pa ~/.rcrc
.Sh EXAMPLES
.Dl chrc -O rcrc
.Dl chrc -D work-dotfiles tigrc
.Dl chrc -O -D public-dotfiles gitconfig
.Dl chrc -U pythonrc bpythonrc piprc
.Dl chrc -T scala -D community-dotfiles sbt
.Sh SEE ALSO
.Xr lsrc 1 ,
.Xr mkrc 1 ,
.Xr rcdn 1 ,
.Xr rcup 1 ,
.Xr rcrc 5 ,
.Xr rcm 7
.Sh AUTHORS
.An "Mike Burns" Aq mike@mike-burns.com
