.Dd July 28, 2013
.Dt MKRC 1
.Os
.Sh NAME
.Nm mkrc
.Nd bless files into a dotfile
.Sh SYNOPSIS
.Nm mkrc
.Op Fl vq
.Op Fl t Ar tag
.Op Fl d Ar dir
.Ar files ...
.Sh DESCRIPTION
This program adds files to your dotfiles directory then installs it
back into your home directory. It can install files under a tag or
different source directory.
.
It supports these options:
.
.Bl -tag
.It Fl v
increase verbosity. This can be repeated for extra verbosity.
.It Fl q
decrease verbosity
.It Fl t Ar TAG
install dotfiles according to tag
.It Fl d Ar DIR
install dotfiles under the specified directory. This can be specified
multiple times.
.El
.Sh FILES
.Pa ~/.dotfiles
.Pa ~/.rcrc
.Sh EXAMPLES
.Dl mkrc ~/.vimrc
.Dl mkrc -t zsh -d company-dotfiles ~/.zshrc ~/.zlogin
.Sh SEE ALSO
.Xr lsrc 1 ,
.Xr rcup 1 ,
.Xr rcrc 5 ,
.Xr rcm 7
.Sh AUTHORS
.An "Mike Burns" Aq mike@mike-burns.com
